### ISSUE TITLE
رفع مشکل خواندن فایلها

### ISSUE THREAD

**Issue by hosseinip** [mojtaba-khallash/NHazm#1]
سلام،
در اولین بار اجرای ابزار به مشکلی برخودم که البته خیلی ساده بود و با توجه به حل مشکل خواستم راه حل رو اینجا به اشتراک بگذارم.
مشکل در پیدا کردن آدرس برخی از فایلهایی بود که در پروژه استفاده شدند.
به عنوان مثال آدرس فایل لیست واژگان به طور پیشفرض به صورت زیر آمده:

> > > "data/words.dat"

در صورتی که اگر برای خواندن فایل، پروژه دچار اشکال شد میتوانیم از کد زیر استفاده کنیم (که البته به سادگی با پیدا کردن آدرس دایرکتوری فایل را میخواند):

> > > Path.GetDirectoryName(Path.GetDirectoryName(System.IO.Directory.GetCurrentDirectory())) + "/data/words.dat"

**Comment by mojtaba-khallash** [comment]
سلام
برای حل این مشکل لزومی به تغییر در کتابخانه نیست. این پوشه باید در کنار 
NHazm.dll
باشد تا کار کند. از این آدرس دهی تنها در کلاس لمتایزر استفاده شده است که دارای چهار نوع سازنده است. اگر سازنده پیش فرض فراخوانی شود از آدرس
data/words.dat
استفاده خواهد شد اما شما می‌تونید با استفاده از سایر سازنده‌های این کلاس آدرس دقیق فایل مورد نظر خود که ممکن است هر جای دیگری باشد بدهید
دلیل اصلی که از روش پیشنهادی شما استفاده نشده است پاس شدن تست‌هاست. در کنار پروژه هضم یک پروژه تست قرار دارد که در صورت استفاده از روش شما آدرس این فایل به فولدری که پروژه تست هست اشاره خواهد کرد که در این صورت این فایل‌ها باید در پروژه تست هم کپی شوند. اما با روش موجود نیازی به این کار نخواهد بود و از فایل موجود در پروژه اصلی استفاده خواهد شد
