### ISSUE TITLE
persian postager in C#

### ISSUE THREAD

**Issue by rezaee96** [mojtaba-khallash/NHazm#14]
سلام . من از ان هضم استفاده کردم ولی در بخش پستاگر اصلا مدل پرشین تاگر رو شناسایی نمی کنه و خطا میده هرچند این  فایل رو در پوشه ای به عنوان ریسورس کنار پروژه سی شارپ قرار دادم. لطفا راهنمایی کنید مشکل چی هستش؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟

**Comment by mojtaba-khallash** [comment]
سلام
توضیحات خیلی ناقص هست ولی احتمالا به این خاطره که وابستگی ها رو آپدیت کردید

این مورد در #4 هم مطرح شده بود ([اینجا](https://github.com/mojtaba-khallash/NHazm/issues/4#issuecomment-180032154) را بخونید).

> این پروژه با نسخه های زیر کار می کند:
> 
>     Stanford.NLP.POSTagger.3.3.1.1
>     MaltParser.1.8.0.0
>     IKVM.7.4.5196.0
>

**Comment by rezaee96** [comment]
من تمام این ها رو اضافه کردم متاسفانه....

**Comment by rezaee96** [comment]
سلام من مشکلم حل کردم. من موارد فوق رو اضافه کرده بودم ولی فریمورک دات نت من نسخه 4.5.2 بود. با تغییر آن به 4.5  برام اجرا شد

**Comment by mojtaba-khallash** [comment]
ممنون که راه حل رو به اشتراگ گذاشتید

**Comment by rezaee96** [comment]
خواهش  میکنم
    On Wednesday, March 21, 2018, 3:01:50 PM GMT+3:30, Mojtaba Khallash <notifications@github.com> wrote:  
 
 
ممنون که راه حل رو به اشتراگ گذاشتید
