### ISSUE TITLE
chunker

### ISSUE THREAD

**Issue by djcesb** [mojtaba-khallash/NHazm#2]
سلام
همونطور که توی راهنمای استفاده از برنامه هضم(کد پایتون) در سایت قرار دادید قسمتی تحت عنوان چانکر وجود داره
آیا چانکر در برنامه ان.هضم(کد سی شارپ) هم وجود داره؟؟
اگر وجود داره لطفا راهنمایی کنید چطور میشه ازش استفاده کرد
ممنون

**Comment by mojtaba-khallash** [comment]
سلام
نه در نسخه سی شارپ این امکان وجود ندارد
نسخه سی شارپ معادل نسخه 0.1 کد پایتون هضم هست که در آن نسخه چانکر وجود نداشت

**Comment by kzcom** [comment]
سلام
آیا نسخه های سی شارپ و پایتون هضم از لحاظ دقت ابزارهای آن با هم فرق می کنند؟ و تمام آپدیت ها را برای نسخه سی شارپ نیز انجام می دهید؟

**Comment by hosseinip** [comment]
آنچه مشخص هست و فکر میکنم قبلا هم دوستان سوال کردند، فکر نمیکنم که کلا نسخه های سی شارپ و جاوا همگام با نسخه اصلی پایتون به روز بشند. خود جناب خلاش هم میتونند در این مورد توضیح بدند

**Comment by mojtaba-khallash** [comment]
نسخه های سی شارپ و جاوا عینا مطابق با نسخه 0.1 از پایتون هضم توسعه داده شد
به دلایلی همگام با نسخه پایتون جلو نرفت و در همان نسخه 0.1 باقی مانده است

**Comment by kzcom** [comment]
من نیاز به استفاده از ابزاهای آن خصوصا  چانکر در محیط سی شارپ دارم. ایا امکان استفاده از کدهای پایتون در این محیط می باشد؟ 

```
 On Wednesday, October 14, 2015 10:35 PM, Mojtaba Khallash <notifications@github.com> wrote:
```

 نسخه های سی شارپ و جاوا عینا مطابق با نسخه 0.1 از پایتون هضم توسعه داده شد
به دلایلی همگام با نسخه پایتون جلو نرفت و در همان نسخه 0.1 باقی مانده است—

**Comment by mojtaba-khallash** [comment]
تجربه استفاده از کد پایتون در سی شارپ رو ندارم ولی یک زبان
IronPython
وجود داره که شاید ه درد بخوره

برای زبان جاوا یک کتابخانه
OpenNLP
هست که تبدیل شده آن برای سی شارپ با نام
SharpNLP
قابل استفاده هست. این ابزار
chunker
هم داره
