### ISSUE TITLE
استخراج اخبار از پیکره همشهری

### ISSUE THREAD

**Issue by kzcom** [mojtaba-khallash/NHazm#3]
با سلام
 چطور می توان خبرهای یک روز خاص همشهری را استخراج کنیم؟
( مثلا" متن اخبار روز1997/05/25 )
 String year="1997";
 String month="05";
 String day="25";
 String news="all texts in that day using hamshahriReader.cs..."

**Comment by mojtaba-khallash** [comment]
سلام
این ابزار محلی که فایل های همشهری در آن قرار دارد دریافت می کند و همه را می خواند

> GetDocuments()
> این تابع تمام اسناد را برمی گرداند

برای این نیاز شما دو تابع جدید اضافه کردم

> GetDocuments(DateTime date)
> این تابع یک تاریخ مشخص را دریافت می کند و اسناد همان فایل را برمی گرداند
> GetDocuments(DateTime start, DateTime end)
> این تابع دو تاریخ را دریافت کرده و تمام اسناد موجود در این بازه را برمی گرداند

**Comment by kzcom** [comment]
سلام
ضمن تشکر از پاسخ شما، اگر نحوه استفاده از توابع پیاده سازی شده جدید را بفرمایید ممنون می شوم. متاسفانه کدهای زیر جواب نمی دهند! 
            var hr = new HamshahriReader();
            DateTime date1 = new DateTime(1996, 06, 2, 0, 0, 0);
            DateTime date2 = new DateTime(1998, 06, 2, 0, 0, 0);
            var iter1 = hr.GetDocuments(date1).GetEnumerator();
            var iter2 = hr.GetDocuments(date1,date2).GetEnumerator();
            while (iter1.MoveNext())
            {
                textBox1.Text += iter1.Current.Body+"\n";
            }
            while (iter2.MoveNext())
            {
                textBox2.Text += iter2.Current.Body + "\n";
}
            }
البته به نظر می رسد در تعریف فایل های معتبر همشهری، تما اسناد سالهای2005، 2006 و 2007 پیکره در نظر گرفته نشده اند که بهتر است اصلاح گردد.
invalidFiles = new string[] {"hamshahri.dtd", "HAM2-960622.xml", "HAM2-960630.xml",
.
.
.
"HAM2-050407.xml", "HAM2-050416.xml"};
با تشکر از زحمات ارزشمندتان.

**Comment by mojtaba-khallash** [comment]
سلام
کد مشکلی نداره و نحوه استفاده همینه
مورد اول) اولی جواب نداره چون دقیقا دنبال 
`1996/HAM2-960602.xml`
می گرده که وجود نداره
مورد دوم) اون لیست فایل های نامعتبر هست که امکان پارس اون ها وجود ندارد. اگر همه را وارد کنید از همه رد خواهد شد
مورد سوم) اگر بازهم مشکل دارید شاید 
`culture`
بر روی تاریخ اثر گذاشته. چک کنید ممکنه خروجی

> DateTime.Now => {12/09/1394 11:23:44 ب.ظ}

باشد. در اینصورت بهتره با کد زیر مشکل را حل کنید

> Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-US");

**Comment by kzcom** [comment]
چرا فایل های مربوطه نامعتبر هستند و امکان پارس ندارند؟

**Comment by mojtaba-khallash** [comment]
چون داره این خطاها رو میده

> {"Data at the root level is invalid. Line 1, position 1."}
> {"'\u001d', hexadecimal value 0x1D, is an invalid character. Line 1, position 1."}
> {"Invalid character in the given encoding. Line 1, position 1."}

**Comment by kzcom** [comment]
با عرض سلام ، خسته نباشید و تشکر ویژه از پاسخگویی های مهندس خلاش
چند سوال در مورد نسخه سی شارپ هضم:
1- دقت ابزارهای برچسبگذار و تجزیه گر نحوی آخرین نسخه سی شارپ هضم چند/چگونه است؟
 2- لیست دقیق تگ های مورد استفاده در طراحی آنها چه می باشند؟
3- چطور می توانیم برای هر جمله ورودی، برچسب های مربوط به تجزیه گر وابستگی هر کلمه آن را تعیین کنیم؟ به عبارتی دیگر نحوه استفاده از کدها برای استخراج برچسب های تچزیه گر وابستگی هر کلمه چطور می باشد:
DependencyParser parser = new DependencyParser();
string[] input = new string[] {"this","is","a","test"};
string[] tagsParser=?? 
String[] indexesParser=??

**Comment by mojtaba-khallash** [comment]
سوال شما ارتباطی با 
issue
جاری ندارد و از طرفی بسته شده است. لطفا اگر موردی هست جداگانه مطرح کنید
1.
  نسخه 1.0 هضم سی شارپ معادل نسخه 0.1 هضم پایتون هست که دقت آن در [اینجا](http://www.sobhe.ir/hazm/) آمده است
- دقت برچسب‌زن صرفی: 96.6 درصد
- دقت تجزیه‌گر نحوی: 83.3 درصد

2.
  سوالات مشابه این در نسخه پایتون پرسیده شده و جواب هم داده شده است. مثل [#39](https://github.com/sobhe/hazm/issues/39) یا [ #41](https://github.com/sobhe/hazm/issues/41) یا [#51](https://github.com/sobhe/hazm/issues/51)
ما برای آموزش برچسب‌زن از [پیکره بیجن خان](http://ece.ut.ac.ir/dbrg/bijankhan/) استفاده کردیم و برای تجزیه وابستگی از [پیکره دادگان](http://www.dadegan.ir/catalog/perdt) استفاده کردیم. هر کدام از این دو پیکره  دارای مجموعه تگ های خاص خودشان هستند. به دلیل عدم سازگاری این دو دسته، خروجی برچسب زن (مجموعه برچسب های بیجن خان) را با استفاده از [این](https://github.com/mojtaba-khallash/NHazm/blob/master/NHazm/data/posMaps.dat) نگاشت تبدیل به برچسب های دادگان کردیم
3.
مدل های هضم برای متن فارسی طراحی شده است و نباید انتظار داشته باشید روی متن انگلیسی درست کار کنند
نحوه استفاده از تمام کدها در [اینجا](https://github.com/mojtaba-khallash/NHazm/tree/master/NHazm.Test) موجود است
