### ISSUE TITLE
تگ های تجزیه گر نحوی

### ISSUE THREAD

**Issue by kzcom** [mojtaba-khallash/NHazm#4]
سلام 
در تجزیه گر نحوی چطور می توان به جای تولید خروجی با ساختار جدولی فقط کلمات، تگ های برچسب زن صرفی و تگ های تجزیه گر نحوی بدست آمده برای جمله ورودی را  جداگانه استخراج/ذخیره کنیم؟
با تشکر

**Comment by mojtaba-khallash** [comment]
سلام
خروجی تجزیه رشته نیست بلکه
ConcurrentDependencyGraph
است. این کلاس توابع زیادی دارد که به راحتی می توان این کار را کرد

> var graph = parser.Parse(input);
> for (var i = 1; i< graph.nDependencyNodes(); i++)
> {
>    var row = graph.getTokenNode(i);
> 
>    var ID = row.getLabel(0);
>    var FORM = row.getLabel(1);
>    var LEMMA = row.getLabel(2);
>    var CPOSTAG = row.getLabel(3);
>    var POSTAG = row.getLabel(4);
>    var FEATS = row.getLabel(5);
>    var HEAD = row.getLabel(6);
>    var DEPREL = row.getLabel(7);
>    var PHEAD = row.getLabel(8);
>    var PDEPREL = row.getLabel(9);
> }

البته این مورد ارتباطی با هضم ندارد و به کار با
[MaltParser](http://sergey-tihon.github.io/MaltParser.NET/index.html)
مربوط می شود

**Comment by kzcom** [comment]
سلام
ضمن تشکر از پاسخ تان، من به لیست دقیق تگ های تولیدی توسط برچسب زن و تجزیه گر نیاز دارم لذا
1-رفتار تجزیه گرنحوی در مورد تگ هایی که در لیست برچسبهای صرفی دادگان نیست چگونه خواهد بود تگ هایی مانند 
AR,INT,MS,...
2- با توجه به آموزش برچسب زن روی پیکره بیجن خان آیا می توان گفت که برچسب زن هضم نیزدقیقا برچسب های موجود در پیکره پردازش شده بیجن خان (حدود40 برچسب صرفی) تولید می کند؟ آیا تبدیل نگاشتی برای برچسب زن نیز انجام گرفته مثلا تگ هایی مانند زیر در پیکره بیجن خان وجود دارد؟
AJ, CONJ,Ne….
تشکر

**Comment by mojtaba-khallash** [comment]
روال کلی کار به این صورت هست که کد آن در [اینجا](https://github.com/sobhe/hazm/blob/master/data.py#L162) موجود است
1. تبدیل برچسب های بیجن خان با استفاده از نگاشت. این نگاشت هنگام خواندن پیکره بیجن خان اعمال می شود
2. آموزش برچسب زن بر روی بیجن خان با برچسب های تبدیل شده
3. اعمال نرمالایزر و لماتایزر بر روی پیکره دادگان و برچسب زنی مجدد توسط برچسب زن آموزش داده شده
4. آموزش تجزیه گر نحوی بر روی پیکره دادگان اصلاح شده

این توضیحات یعنی مجموعه تگ های سیستم تگ های بیجن خان هستند که توسط نگاشت کاهش پیدا کردند.اگر برچسبی خارج از این مجموعه وجود داشته باشد در لیست نگاشت نبوده و مستقیما از تگ های بیجن خان منتقل شده است

نمی توان انتظار داشت تجزیه گر نحوی کلمه با تگی که در آموزش ندیده درست عمل کند. البته اگر یکی از دو سر رابطه نحوی برچسب جدید داشته باشد ممکن است بتواند جواب درست را پیدا کند اما اگر تگ هر دو سر رابطه جدید باشد احتمال اشتباه پیش بینی کردن زیاد خواهد بود

**Comment by naeimrezaeian** [comment]
سلام دوست گرامی 
من ابتدا این کتابخانه را در پرژه نصب میکنم 
Install-Package Stanford.NLP.POSTagger
اما وقتی میخواهم این کتابخنه را نصب کنم 
Install-Package MaltParser

این خطا را میدهد 
Install failed. Rolling back...
Install-Package : Updating 'IKVM 8.1.5717.0' to 'IKVM 8.0.5449.1' failed. Unable to find a version of 'Stanford.NLP.POSTagger' that is compatible with 'IKVM 8.0.5449.1'.
At line:1 char:16
- Install-Package <<<<  MaltParser
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by mojtaba-khallash** [comment]
سلام
خیلی خوب بود اگر مشکلتون رو در یک
issue
مجزا مطرح می کردید

نیازی به نصب با دستور نبود. به محض اجرای پروژه به صورت خودکار وابستگی ها دانلود می شوند
این پروژه با نسخه های زیر کار می کند:

> Stanford.NLP.POSTagger.3.3.1.1
> MaltParser.1.8.0.0
> IKVM.7.4.5196.0

شما وقتی دستور زیر را وارد می کنید آخرین نسخه یعنی 3.6.0 دانلود خواهد شد
[Install-Package Stanford.NLP.POSTagger](https://www.nuget.org/packages/Stanford.NLP.POSTagger/)
این نسخه وابسته به
IKVM (= 8.1.5717)
است. این در حالی است که آخرین نسخه
[Maltparse 1.8.1](https://www.nuget.org/packages/MaltParser/)
با این نسخه کار می کند
IKVM (= 8.0.5449.1)
همین موضوع مشکل ایجاد می کند
یا به همان نسخه پیش فرض برگردید یا نسخه تگر را به نسخه ای سازگار با مالت پارسر برگردانید
مثلا [نسخه 3.5.2](https://www.nuget.org/packages/Stanford.NLP.POSTagger/3.5.2). البته مطمئن نیستم مشکل دیگه ای پیش نیاد
