### ISSUE TITLE
سفارشی سازی تگ های برچسب زن

### ISSUE THREAD

**Issue by kzcom** [mojtaba-khallash/NHazm#5]
سلام
آیا امکان دارد رفتار برچسب زن را بر اساس لیستی از برچسبهای مورد نظر خود و بدون نگاشت اصلاح کنیم؟  به این صورت که اگر برچسب تولیدی کلمه ای، خارج از لیست مذکور باشد برچسب ها را براساس متد دیگری تولید کند لذا روال کار تجزیه گر نحوی نیز براساس این لیست جدید خواهد شد. 
مثلا لیست فرضی ما فقط داری 5 برچسب زیر است و متد ما به این صورت است که با گرفتن جمله ورودی لیستی از برچسب های کلمات آن را برمی گرداند.
string[ ] POStaglist2={"N","ADJ","ADV","V","PUNC"};
Teggermethod(string sentence ,string[] POStags2);
با تشکر.

**Comment by mojtaba-khallash** [comment]
سلام
من متوجه منظورتون نشدم
فرایند رو قبلا توضیح دادم
اگر مجموعه برچسب رو قصد دارید عوض کنید باید یک نگاشت جدید تعریف کنید. پیکره ها را اصلاح و مجدد اموزش دهید
