### ISSUE TITLE
مشکل در دانلود نسخه ikvm

### ISSUE THREAD

**Issue by naeimrezaeian** [mojtaba-khallash/NHazm#6]
سلام دوست گرامی 
من ابتدا این کتابخانه را در پرژه نصب میکنم 
Install-Package Stanford.NLP.POSTagger
اما وقتی میخواهم این کتابخنه را نصب کنم 
Install-Package MaltParser

این خطا را میدهد 
Install failed. Rolling back...
Install-Package : Updating 'IKVM 8.1.5717.0' to 'IKVM 8.0.5449.1' failed. Unable to find a version of 'Stanford.NLP.POSTagger' that is compatible with 'IKVM 8.0.5449.1'.
At line:1 char:16

Install-Package <<<< MaltParser
CategoryInfo : NotSpecified: (:) [Install-Package], InvalidOperationException
FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by naeimrezaeian** [comment]
وقتی وابستگی ها را هم دانلود نکنم و پروژه را اجرا کنم این خطا ها را نمایش میدهد 
[http://naeim.ru/e1.jpg](url)
[http://naeim.ru/e2.jpg](url)

**Comment by mojtaba-khallash** [comment]
سلام
این پروژه با نسخه های زیر کار می کند:

> Stanford.NLP.POSTagger.3.3.1.1
> MaltParser.1.8.0.0
> IKVM.7.4.5196.0

شما وقتی دستور زیر را وارد می کنید آخرین نسخه یعنی 3.6.0 دانلود خواهد شد
[Install-Package Stanford.NLP.POSTagger](https://www.nuget.org/packages/Stanford.NLP.POSTagger/)
این نسخه وابسته به
IKVM (= 8.1.5717)
است. این در حالی است که آخرین نسخه
[Maltparse 1.8.1](https://www.nuget.org/packages/MaltParser/)
با این نسخه کار می کند
IKVM (= 8.0.5449.1)
همین موضوع مشکل ایجاد می کند
یا به همان نسخه پیش فرض برگردید یا نسخه تگر را به نسخه ای سازگار با مالت پارسر برگردانید
مثلا [نسخه 3.5.2](https://www.nuget.org/packages/Stanford.NLP.POSTagger/3.5.2). البته مطمئن نیستم مشکل دیگه ای پیش نیاد
