### ISSUE TITLE
نحوه آموزش سیستم 

### ISSUE THREAD

**Issue by naeimrezaeian** [mojtaba-khallash/NHazm#7]
سلام 
میشه بفرمایید سیستم را اگر من یک پوسته جدید داشته باشم باید چه جوری آموزش بدهم 

و یک سوال هم داشتم من یک جمله که بصورت خودکار در سایت پروژه هضم هست را در کد این برنامه  وارد میکنم ولی جوابی متفاوت میگیرم اگر امکان دارد در این مورد هم توضیح بفرمایید 
جمله 

**> در می‌زند و دوباره وارد مي شود . همه مي گویند قدمش پربرکت است .
*
با تشکر

**Comment by mojtaba-khallash** [comment]
سلام
این سوال قبلا جواب داده شده است
[#4](https://github.com/mojtaba-khallash/NHazm/issues/4)

در این مورد هم قبلا توضیح داده شده است
[#2](https://github.com/mojtaba-khallash/NHazm/issues/2)
نسخه فعلی معادل نسخه 0.1 هضم پایتون است.با توجه به اینکه در حال حاضر نسخه 0.5 هضم منتشر شده است عجیب نخواهد بود که خروجی این دو یکسان نباشد

موفق باشید
