### ISSUE TITLE
راهنمای استفاده از برنامه هضم

### ISSUE THREAD

**Issue by zeinabhoseiny** [mojtaba-khallash/NHazm#8]
سلام.من راهنمای مربوط به استفاده از برنامه هضم رو توی سایتتون پیدا نکردم.لطفا بنده رو راهنمایی بفرمایید.

**Comment by mojtaba-khallash** [comment]
سلام
[تست های](https://github.com/mojtaba-khallash/NHazm/tree/master/NHazm.Test) نوشته در واقع نحوه کار با ابزار رو نشون می دهند

**Comment by zeinabhoseiny** [comment]
سلام.بله پیدا کردم برای همینم issueجدید رو بستم.فقط میشه دقیقا بگید نسخه های هضم از اول هم برای سی شارپ و هم پایتون و جاوا به چه ترتیبی بوده؟برای پروژه ام لازم دارم.-------- Original Message --------Subject: Re: [NHazm] راهنمای استفاده از برنامه هضم (#8)From: Mojtaba Khallash To: mojtaba-khallash/NHazm CC: zeinabhoseiny سلام
تست های نوشته در واقع نحوه کار با ابزار رو نشون می دهند

**Comment by mojtaba-khallash** [comment]
سلام
قبلا چند بار به این سوال جواب داده شده است
سی شارپ و جاوا تنها یک نسخه دارند که معادل نسخه 0.1 پایتون است
